### ISSUE TITLE
A bug in Realm js version crashes the app when using remote debugger.  

### ISSUE THREAD

**Issue by laurisaarni** [billmalarky/react-native-queue#9] opened 2018-03-29 02:26 UTC
Please see the issue https://github.com/realm/realm-js/issues/1711.

Using realm version 2.2.15 fixes the bug.

**Comment by billmalarky** [comment] 2018-03-29 15:56
Looks like that may not resolve it.

https://github.com/realm/realm-js/issues/1711#issuecomment-377091874

**Comment by saarnilauri** [comment] 2018-03-30 02:11
@billmalarky In my case, I had a dependency to Realm in my package.json and to react-native-queue when I changed mine and react-native-queue to use 2.2.15 the problem was gone. I'm not sure if the user claiming it did not work had a similar use case.

**Comment by juliancorrea** [comment] 2018-04-20 11:34
About this issue, see this: https://github.com/facebook/react-native/issues/11989#issuecomment-314111441

**The commit that solve the problem is:** https://github.com/realm/realm-js/pull/1744/files/aed0fa5cd97db9d19b6951815f369ff943d82d20 e was merged on master.

However, there is no release with it, so I've change the file _realm/lib/browser/index.js_ until a new release.

Its necessary change the _realm/lib/user.js_ too, commenting  the line 45, because of the problem that happens next: _Cannot redefine property: logout' problem_.

**Comment by maxhalty** [comment] 2018-04-25 19:32
Hi Guys! do you know when the next release will be? We really need this fix and for now we are commenting the line but that's not a good fix for our team.

**Comment by billmalarky** [comment] 2018-04-27 20:04
@saarnilauri To be clear, if I explicitly set the realm dependency in package.json to "2.2.15" as in the PR below (I'll increment the patch version directly on master) this should resolve the issue to your knowledge (assuming people nuke node_modules [and yarn lockfile] and rerun yarn or npm install)?

https://github.com/billmalarky/react-native-queue/pull/19

**Comment by billmalarky** [comment] 2018-04-27 20:16
Realm is on 2.4.0 now, is this still even an issue?

**Comment by xinhash** [comment] 2018-05-04 11:51
Use this ``adb logcat *:S ReactNative:V ReactNativeJS:V BackgroundTask:V`` to log and debug

**Comment by billmalarky** [comment] 2018-09-23 17:21
Is this still an issue? Realm is on 2.16.1. Can I close this issue?

**Comment by saarnilauri** [comment] 2018-09-24 04:18
Fine by me

**Comment by billmalarky** [comment] 2018-09-24 18:54
👌

**Closed by billmalarky** 2018-09-24 18:54 UTC
